# Generated by Django 2.2 on 2020-03-24 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='galeria',
            options={'ordering': ['id']},
        ),
    ]
