version: '3.1'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
        MYSQL_DATABASE: 'lifebartenders'
        MYSQL_USER: 'lifebartenders'
        MYSQL_PASSWORD: '123456'
        MYSQL_ROOT_PASSWORD: '123456'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
